version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/go/pkg/mod
      - /app/bin
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migrate
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mynance?sslmode=disable

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mynance
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: golang:1.22.1
    command: ["migrate", "-path", "/app/migrations", "-database", "postgres://postgres:postgres@db:5432/mynance?sslmode=disable", "up"]
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  db_data:
