version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mydget
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydget
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mydget"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=mydget
      - DB_PASSWORD=mypassword
      - DB_NAME=mydget
    depends_on:
      db:
        condition: service_healthy